# HYPOTHESIS TESTING OF CATAGORICAL DATA
## By : Deep Contractor

# 1. Half-Century Scored – Home Team Inning 1
# 2. Half Century Scored – Away  Team Inning 1
# 3. Double Century Scored


In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import IPython
from IPython.display import display, HTML
from scipy.stats import ttest_ind
from scipy.stats import chi2_contingency

In [16]:
newdf = pd.read_csv(r'C:\Users\deepc\Desktop\Data Work\hypothesis_data_IW.csv')

In [17]:
newdf["No_of_50s_HT"]=newdf.No_of_50s_HT.astype(int)
newdf["No_of_50s_AT"]=newdf.No_of_50s_AT.astype(int)
newdf["Double_Century_AT"]=newdf.Double_Century_AT.astype(int)
newdf["Double_Century_HT"]=newdf.Double_Century_HT.astype(int)

In [18]:
#display(HTML(newdf.to_html()))
newdf.head()

Match_ID     Home_Team  No_of_50s_HT  Double_Century_HT  Away_Team  \
0   1000851  South Africa             2                  0  Australia   
1   1000853  South Africa             2                  0  Australia   
2   1000855  South Africa             1                  0  Australia   
3   1000881     Australia             3                  0   Pakistan   
4   1000883      Pakistan             3                  1  Australia   

   No_of_50s_AT  Double_Century_AT  
0             2                  0  
1             0                  0  
2             4                  0  
3             1                  0  
4             5                  0

In [19]:
data = pd.read_csv(r'C:\Users\deepc\Desktop\Data Work\hypo.csv')

# The data below shows how many times a team has scored half centuries

In [20]:
data

team  zero  one  two  three  four  five  six
0           South Africa     8   15   26     20    13     5    0
1              Australia     9   20   29     26    16    11    2
2               Pakistan    12   12   18     15    15     3    0
3       Papua New Guinea     0    2    0      0     0     0    0
4            New Zealand    13   24   17     13    11     5    1
5                  India     8   16   24     26    13    11    2
6            West Indies    12   22   23     14     5     3    1
7               Zimbabwe     3    5    4      5     1     0    0
8                England    13   15   38     27    22     6    0
9             Bangladesh     8   15    8     13     3     2    0
10             Sri Lanka    11   19   23     14    11     3    1
11           Netherlands     0    0    1      0     0     0    0
12               Ireland     1    2    0      0     0     0    0
13             Hong Kong     0    0    0      1     1     0    0
14               Namibia     1    1    0      0     0     0    0
15           Afghanistan     0    1    0      1     0     0    0
16  United Arab Emirates     0    1    0      0     0     0    0

In [21]:
for i in range(len(data)):
    if(data['zero'][i]==0):
        data.loc[i,1:2]='False'
    else:
         data.loc[i,1:2]='True'
    if(data['one'][i]==0):
        data.loc[i,2:3]='False'
    else:
         data.loc[i,2:3]='True'
    if(data['two'][i]==0):
        data.loc[i,3:4]='False'
    else:
         data.loc[i,3:4]='True'
    if(data['three'][i]==0):
        data.loc[i,4:5]='False'
    else:
         data.loc[i,4:5]='True'
    if(data['four'][i]==0):
        data.loc[i,5:6]='False'
    else:
         data.loc[i,5:6]='True'
    if(data['five'][i]==0):
        data.loc[i,6:7]='False'
    else:
         data.loc[i,6:7]='True'
    if(data['six'][i]==0):
        data.loc[i,7:8]='False' 
    else:
         data.loc[i,7:8]='True'
        

In [22]:
data

team   zero    one    two  three   four   five    six
0           South Africa   True   True   True   True   True   True  False
1              Australia   True   True   True   True   True   True   True
2               Pakistan   True   True   True   True   True   True  False
3       Papua New Guinea  False   True  False  False  False  False  False
4            New Zealand   True   True   True   True   True   True   True
5                  India   True   True   True   True   True   True   True
6            West Indies   True   True   True   True   True   True   True
7               Zimbabwe   True   True   True   True   True  False  False
8                England   True   True   True   True   True   True  False
9             Bangladesh   True   True   True   True   True   True  False
10             Sri Lanka   True   True   True   True   True   True   True
11           Netherlands  False  False   True  False  False  False  False
12               Ireland   True   True  False  False  False  False  False
13             Hong Kong  False  False  False   True   True  False  False
14               Namibia   True   True  False  False  False  False  False
15           Afghanistan  False   True  False   True  False  False  False
16  United Arab Emirates  False   True  False  False  False  False  False

# Testing the data for "Zero"

# Approch used : chi-square statistic - χ2

In [23]:
#contingency table
contingency_table=pd.crosstab(data["team"],data["zero"])

In [24]:
contingency_table

zero                  False  True
team                             
Afghanistan               1     0
Australia                 0     1
Bangladesh                0     1
England                   0     1
Hong Kong                 1     0
India                     0     1
Ireland                   0     1
Namibia                   0     1
Netherlands               1     0
New Zealand               0     1
Pakistan                  0     1
Papua New Guinea          1     0
South Africa              0     1
Sri Lanka                 0     1
United Arab Emirates      1     0
West Indies               0     1
Zimbabwe                  0     1

In [25]:
#Observed Values
Observed_Values = contingency_table.values 
print("Observed Values :-\n",Observed_Values)

Observed Values :-
 [[1 0]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]]


In [26]:
#Expected Values
import scipy.stats
b=scipy.stats.chi2_contingency(contingency_table)
Expected_Values = b[3]
print("Expected Values :-\n",Expected_Values)

Expected Values :-
 [[0.29411765 0.70588235]
 [0.29411765 0.70588235]
 [0.29411765 0.70588235]
 [0.29411765 0.70588235]
 [0.29411765 0.70588235]
 [0.29411765 0.70588235]
 [0.29411765 0.70588235]
 [0.29411765 0.70588235]
 [0.29411765 0.70588235]
 [0.29411765 0.70588235]
 [0.29411765 0.70588235]
 [0.29411765 0.70588235]
 [0.29411765 0.70588235]
 [0.29411765 0.70588235]
 [0.29411765 0.70588235]
 [0.29411765 0.70588235]
 [0.29411765 0.70588235]]


In [27]:
#Degree of Freedom
no_of_rows=len(contingency_table.iloc[0:2,0])
no_of_columns=len(contingency_table.iloc[0,0:2])
df=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",df)


Degree of Freedom:- 1


In [28]:
#Significance Level 5%
alpha=0.05

In [29]:
#chi-square statistic - χ2
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]
print("chi-square statistic:-",chi_square_statistic)

chi-square statistic:- 17.0


In [30]:
#critical_value
critical_value=chi2.ppf(q=1-alpha,df=df)
print('critical_value:',critical_value)

critical_value: 3.841458820694124


In [31]:
#p-value
p_value=1-chi2.cdf(x=chi_square_statistic,df=df)
print('p-value:',p_value)

p-value: 3.7379818401683806e-05


In [32]:
print('Significance level: ',alpha)
print('Degree of Freedom: ',df)
print('chi-square statistic:',chi_square_statistic)
print('critical_value:',critical_value)
print('p-value:',p_value)

Significance level:  0.05
Degree of Freedom:  1
chi-square statistic: 17.0
critical_value: 3.841458820694124
p-value: 3.7379818401683806e-05


In [33]:
#compare chi_square_statistic with critical_value and p-value which is the probability of getting chi-square>0.09 (chi_square_statistic)
if chi_square_statistic>=critical_value:
    print("Reject H0,There is a relationship between the categorical variables")
else:
    print("Retain H0,There is no relationship between the categorical variables")
    
if p_value<=alpha:
    print("Reject H0,There is a relationship between the categorical variables")
else:
    print("Retain H0,There is no relationship between the categorical variables")

Reject H0,There is a relationship between the categorical variables
Reject H0,There is a relationship between the categorical variables


# Testing the data for "one"

# chi-square statistic - χ2

In [34]:
#contingency table
contingency_table=pd.crosstab(data["team"],data["one"])

In [35]:
contingency_table

one                   False  True
team                             
Afghanistan               0     1
Australia                 0     1
Bangladesh                0     1
England                   0     1
Hong Kong                 1     0
India                     0     1
Ireland                   0     1
Namibia                   0     1
Netherlands               1     0
New Zealand               0     1
Pakistan                  0     1
Papua New Guinea          0     1
South Africa              0     1
Sri Lanka                 0     1
United Arab Emirates      0     1
West Indies               0     1
Zimbabwe                  0     1

In [36]:
#Observed Values
Observed_Values = contingency_table.values 
print("Observed Values :-\n",Observed_Values)

Observed Values :-
 [[0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]


In [37]:
#Expected Values
import scipy.stats
b=scipy.stats.chi2_contingency(contingency_table)
Expected_Values = b[3]
print("Expected Values :-\n",Expected_Values)

Expected Values :-
 [[0.11764706 0.88235294]
 [0.11764706 0.88235294]
 [0.11764706 0.88235294]
 [0.11764706 0.88235294]
 [0.11764706 0.88235294]
 [0.11764706 0.88235294]
 [0.11764706 0.88235294]
 [0.11764706 0.88235294]
 [0.11764706 0.88235294]
 [0.11764706 0.88235294]
 [0.11764706 0.88235294]
 [0.11764706 0.88235294]
 [0.11764706 0.88235294]
 [0.11764706 0.88235294]
 [0.11764706 0.88235294]
 [0.11764706 0.88235294]
 [0.11764706 0.88235294]]


In [38]:
#Degree of Freedom
no_of_rows=len(contingency_table.iloc[0:2,0])
no_of_columns=len(contingency_table.iloc[0,0:2])
df=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",df)


Degree of Freedom:- 1


In [39]:
#Significance Level 5%
alpha=0.05

In [40]:
#chi-square statistic - χ2
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]
print("chi-square statistic:-",chi_square_statistic)

chi-square statistic:- 16.999999999999993


In [41]:
#critical_value
critical_value=chi2.ppf(q=1-alpha,df=df)
print('critical_value:',critical_value)

critical_value: 3.841458820694124


In [42]:
#p-value
p_value=1-chi2.cdf(x=chi_square_statistic,df=df)
print('p-value:',p_value)

p-value: 3.7379818401683806e-05


In [43]:
print('Significance level: ',alpha)
print('Degree of Freedom: ',df)
print('chi-square statistic:',chi_square_statistic)
print('critical_value:',critical_value)
print('p-value:',p_value)

Significance level:  0.05
Degree of Freedom:  1
chi-square statistic: 16.999999999999993
critical_value: 3.841458820694124
p-value: 3.7379818401683806e-05


In [44]:
#compare chi_square_statistic with critical_value and p-value which is the probability of getting chi-square>0.09 (chi_square_statistic)
if chi_square_statistic>=critical_value:
    print("Reject H0,There is a relationship between the categorical variables")
else:
    print("Retain H0,There is no relationship between the categorical variables")
    
if p_value<=alpha:
    print("Reject H0,There is a relationship between the categorical variables")
else:
    print("Retain H0,There is no relationship between the categorical variables")

Reject H0,There is a relationship between the categorical variables
Reject H0,There is a relationship between the categorical variables
